@startuml
start

:Read the **token** from **xing_csrf_token** cookie;

if (**token** is defined?) then (yes)
    :Set **X-CSRF-Token** header for the request with **token** as a value;
else (no)
endif

:Send the request;

stop
@enduml
